### PR TITLE
Initial port to JupyterLab 3 prebuilt extension.

### PR DESCRIPTION
**Pull request by jasongrout**
This also adds a license file (BSD-3-CLAUSE), with @wolfv as the copyright owner.

Wolf, if you want to eventually transfer this to the jlab organization, I would like to iterate on this some more.

### CODE REVIEW

**Comment by jasongrout** [comment]
This seems to work okay in JupyterLab 3 now as a prebuilt extension:

Here we write a short extension that adds a command palette item in a text file, then loads the extension into JupyterLab:

dynamicextension

**Comment by jasongrout** [comment]
I've commented out the widget support for now...

**Comment by jasongrout** [comment]
@wolfv - can I have write permissions on this repo? Thanks.

**Comment by wolfv** [comment]
Hey @jasongrout yes, of course! Happy to transfer it anywhere you would like, too

**Comment by wolfv** [comment]
hmm, somehow it seems that I can't make you admin on a personal repo?! didn't know that :)

Anyways, as I said, more than happy to transfer this repo wherever you think is best!

Really cool to see you iterating on this :)

**Comment by jasongrout** [comment]
> hmm, somehow it seems that I can't make you admin on a personal repo?! didn't know that :)

I think you can make me a collaborator from https://github.com/wolfv/jupyterlab-dynext/settings/access, though.

**Comment by wolfv** [comment]
I made you a collaborator already :)

**Comment by jasongrout** [comment]
> I made you a collaborator already :)

Oh. I thought that would let me close issues, etc., but apparently not.

I'll ask during the dev meeting on Wednesday if we can transfer to the JupyterLab organization. Thanks again!

**Pull request merged**
